### ISSUE TITLE
Add Nendoroid doll data

### ISSUE THREAD

**Issue by silvershort** [KhoraLee/NendoroidDB#5]
혹시 넨도돌 정보를 추가할 수 있을까요?
꼭 필요한 기능은 아니고 넨도돌 정보를 원하는 앱사용자가 있어서 혹시 쉽게 추가가 가능한지 문의드려봅니다.
* * *
### TODO :
- [x] 넨도로이드 돌 DB 추가

**Comment by KhoraLee** [comment]
지금 굿스마 홈페이지 파서를 처음부터 다시 작성하고 있어서 바로는 안되지만 가능은 하긴 합니다.
넨도 정보 처럼 예전 넨갤 시트에 돌/옷 정리된 내용이 있어서 최근 추가된것만 수기로 작성하면 되서 이번달 내로 반영해보도록하겠습니다.

**Comment by KhoraLee** [comment]
```
.
└── Nendoroid
    ├── 0000-0099
    │   ├── 000.json
    │   ├── ...
    │   └── 099.json
    ├── ...
    ├── Set
    │   ├── Set001.json
    │   └── ...
    ├── Body
    │   ├── Body001.json
    │   └── ...
    ├── Clothes
    │   ├── Cloth001.json
    │   └── ...
    └── Doll
        ├── Doll001.json
        └── ...
  ```
넨도돌 정보가 추가되면 폴더 구조는 이런식으로 될 예정입니다.

넨도처럼 넘버링이 있는게 아니라서 세트형식처럼 일렬번호처럼 하나씩 번호 늘리면서 저장될 예정입니다.
옷만 있는 버전하고 바디랑 옷이랑 같이 있는 버전이 따로라서
옷만([13598](https://www.goodsmile.info/en/product/13598)) 있는게 `Clothes` 폴더에
바디하고 같이([13597](https://www.goodsmile.info/en/product/13597)) 있는게 `Doll` 폴더에 반영될거고
색깔 바디들은 성별 구분해서 `Body` 폴더에 추가 하도록 하겠습니다.

**Comment by KhoraLee** [comment]
현 넨도 세트 정보에 넨도돌이 있으면 이를 추가할지는 고민 중이니 의견 있으시면 남겨주시면 고려해보도록 하겠습니다.

**Comment by silvershort** [comment]
넨도돌 추가도 가능하다니 감사합니다! 폴더 구조도 좋은 것 같네요.

세트정보 추가의 경우
넨돌 세트정보가 당장은 필요없을 것 같긴한데 세트 정보를 원하는 사람들도 있을 것 같고...
또 추가한다면 기존 세트 정보에 같이 있는게 좋을지 아니면 넨돌 세트 데이터를 따로 빼는게 좋을지...
이런 여러가지 생각이 많이 들게 되네요.

결론은 어떤식으로 진행되든 앱에서 구현하는 방식은 비슷비슷할 것 같아서
DB관리자님이 편하신 방향대로 진행해주시면 될 것 같습니다 !

**Comment by KhoraLee** [comment]
ETA: 23.1.8

Planning DB folder structure :
```
.
├── Nendoroid
│   ├── 0000-0099
│   │   ├── 000.json
│   │   ├── ...
│   │   └── 099.json
│   └── Set
│       ├── Set001.json
│       └── ...
└── NendoroidDoll
    ├── Body(or Archetype)
    │   ├── Body001.json
    │   └── ...
    ├── Clothes(or Outfit)
    │   ├── Cloth001.json
    │   └── ...
    ├── Customizing (Such as Hand parts set or Head...)
    │   └── ...
    └── Doll(or Set)
        ├── Doll001.json
        └── ...
```

**Comment by KhoraLee** [comment]
> ```
> .
> ├── Nendoroid
> │   ├── 0000-0099
> │   │   ├── 000.json
> │   │   ├── ...
> │   │   └── 099.json
> │   └── Set
> │       ├── Set001.json
> │       └── ...
> └── NendoroidDoll
>     ├── Body(or Archetype)
>     │   ├── Body001.json
>     │   └── ...
>     ├── Clothes(or Outfit)
>     │   ├── Cloth001.json
>     │   └── ...
>     ├── Customizing (Such as Hand parts set or Head...)
>     │   └── ...
>     └── Doll(or Set)
>         ├── Doll001.json
>         └── ...
> ```

예정된 폴더 구조는 유지 하나 파일명은 GSC 상품 번호를 이용하기로 함.
